### PR TITLE
When throwing errors, mention expected/received values

### PR DESCRIPTION
**Pull request by rolodato**
Also changed strings to single-quote when not interpolating.

### CODE REVIEW

**Comment by excpt** [comment]
:+1: Thanks :-)

**Comment by ZhangHanDong** [comment]
Why must change single-quote?   
http://viget.com/extend/just-use-double-quoted-ruby-strings

**Comment by excpt** [comment]
@ZhangHanDong It's just a code convention or best practice. It's not about speed or anything. It's common to use single quotes for all strings unless you have to pass some values to the string then you use double quotes "Hi #{name}".

**Comment by ZhangHanDong** [comment]
@excpt  I see,  just  i like use double quoted .  all right.   : )

**Comment by rolodato** [comment]
Yes, it's the convention and it's clearer to see at a first glance if something's being replaced or it's a constant string. Also, some IDEs like RubyMine mark it as a warning by default (double-quote string without interpolation).

**Pull request merged**
